package by.htp3.hotel.controller;

public enum CommandName {
	LOGINATION, REGISTRATION, GET_ALL_ROOMS, ADD_NEW_ROOM,
	
	CHANGE_LANGUAGE, ADD_NEW_ROOM_FORM, ADD_NEW_USER_FORM, 
	
	GET_ALL_USERS, DELETE_USER
}
